id: I1CA51B16
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T11:29:27+00:00'
last_modified: '2022-06-08T02:06:17.547564+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15973
  title: མངོན་བརྗོད་མཁས་པའི་རྣ་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    111B:
      image_group_id: I4735
      title: ''
      total_pages: 218
      order: 1
      base_file: 111B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
