id: P004583
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W15973
  title: མངོན་བརྗོད་མཁས་པའི་རྣ་རྒྱན
  author: ''
  volumes:
    c3d76000a86b410797680df0516a7b29:
      image_group_id: I4735
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
